[package]
name = "logwise_proc"
version = "0.4.0"
edition = "2024"
description = "procmacro crate for logwise"
license = "MIT OR Apache-2.0"

[dependencies]

[dev-dependencies]
logwise = { path = "../"}

[lib]
proc-macro =  true
